name: Android Appium CI with Emulator

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
      PATH: ${{ runner.temp }}/android-sdk/cmdline-tools/latest/bin:${{ runner.temp }}/android-sdk/platform-tools:$PATH

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y unzip wget

      - name: Download and setup Android SDK cmdline-tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          mkdir -p latest
          mv cmdline-tools/* latest/
          rm -rf cmdline-tools.zip cmdline-tools

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install required Android SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-33" "emulator" "system-images;android-33;google_apis;x86_64"

      - name: Verify avdmanager is available
        run: |
          ls -l $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/
          avdmanager --version

      - name: Setup Node.js and install Appium
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Appium CLI
        run: npm install -g appium

      - name: Run tests
        run: mvn clean test