name: Android Appium CI with Emulator

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          mkdir -p $ANDROID_SDK_ROOT
          cd $ANDROID_SDK_ROOT
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/

      - name: Accept Android SDK licenses
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

      - name: Install emulator and system image
        run: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "emulator" "system-images;android-33;google_apis;x86_64"

      - name: Create AVD
        run: |
          echo "no" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd -n test_emulator -k "system-images;android-33;google_apis;x86_64" --force

      - name: Start Emulator
        run: |
          $ANDROID_SDK_ROOT/emulator/emulator -avd test_emulator -no-window -no-audio -no-snapshot &

      - name: Wait for emulator boot
        run: |
          adb wait-for-device
          boot_completed=""
          while [[ "$boot_completed" != "1" ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed 2>&1 | tr -d '\r')
            echo "Boot completed: $boot_completed"
            sleep 5
          done

      - name: Install Node.js & Appium
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium CLI
        run: npm install -g appium

      - name: Start Appium Server
        run: nohup appium &

      - name: Wait for Appium to start
        run: |
          n=0
          until curl -s http://localhost:4723/status | grep '"ready":true'; do
            n=$((n+1))
            if [ $n -gt 30 ]; then
              echo "Appium server failed to start"
              exit 1
            fi
            sleep 2
          done

      - name: Run tests
        run: mvn clean test
